export const themes = {
  cyberpunk: {
    name: 'Cyberpunk',
    font: "'Share Tech Mono', monospace",
    displayFont: "'Bebas Neue', sans-serif",
    ui: {
      bg:         '#0a0a0f',
      panel:      '#12121a',
      border:     '#1e1e2e',
      text:       '#c8d0e0',
      textDim:    '#4a5268',
      accent:     '#00ffcc',
      accentGlow: 'rgba(0,255,204,0.4)',
    },
    colors: {
      default:        '#1a2a4a',
      default_border: '#2a3a5a',
      active:         '#00ffcc',
      compare:        '#ff3366',
      pivot:          '#ffaa00',
      sorted:         '#22cc88',
    },
  },

  synthwave: {
    name: 'Synthwave',
    font: "'Share Tech Mono', monospace",
    displayFont: "'Bebas Neue', sans-serif",
    ui: {
      bg:         '#0d0015',
      panel:      '#150020',
      border:     '#2a0a3a',
      text:       '#e8d0ff',
      textDim:    '#6a4a7a',
      accent:     '#ff00ff',
      accentGlow: 'rgba(255,0,255,0.4)',
    },
    colors: {
      default:        '#1a0a2a',
      default_border: '#2a1a3a',
      active:         '#ff00ff',
      compare:        '#00ffff',
      pivot:          '#ffaa00',
      sorted:         '#aa00ff',
    },
  },

  matrix: {
    name: 'Matrix',
    font: "'Share Tech Mono', monospace",
    displayFont: "'Bebas Neue', sans-serif",
    ui: {
      bg:         '#000300',
      panel:      '#000a00',
      border:     '#003300',
      text:       '#00bb00',
      textDim:    '#005500',
      accent:     '#00ff41',
      accentGlow: 'rgba(0,255,65,0.4)',
    },
    colors: {
      default:        '#001a00',
      default_border: '#003300',
      active:         '#00ff41',
      compare:        '#00aa22',
      pivot:          '#88ff00',
      sorted:         '#006600',
    },
  },

  bloodmoon: {
    name: 'Blood Moon',
    font: "'Share Tech Mono', monospace",
    displayFont: "'Bebas Neue', sans-serif",
    ui: {
      bg:         '#0f0000',
      panel:      '#1a0000',
      border:     '#2e0a0a',
      text:       '#ffcccc',
      textDim:    '#6a3333',
      accent:     '#ff2200',
      accentGlow: 'rgba(255,34,0,0.4)',
    },
    colors: {
      default:        '#2a0a0a',
      default_border: '#3a1a1a',
      active:         '#ff2200',
      compare:        '#ff6600',
      pivot:          '#ffcc00',
      sorted:         '#880000',
    },
  },

  arctic: {
    name: 'Arctic',
    font: "'Share Tech Mono', monospace",
    displayFont: "'Bebas Neue', sans-serif",
    ui: {
      bg:         '#f0f8ff',
      panel:      '#e0efff',
      border:     '#b0ccee',
      text:       '#1a2a3a',
      textDim:    '#7a99bb',
      accent:     '#0066cc',
      accentGlow: 'rgba(0,102,204,0.3)',
    },
    colors: {
      default:        '#c8ddf0',
      default_border: '#a8c4e0',
      active:         '#0066cc',
      compare:        '#cc0044',
      pivot:          '#ee8800',
      sorted:         '#00aa66',
    },
  },

  sandstorm: {
    name: 'Sandstorm',
    font: "'Share Tech Mono', monospace",
    displayFont: "'Bebas Neue', sans-serif",
    ui: {
      bg:         '#1a1408',
      panel:      '#241c0c',
      border:     '#3a2e1a',
      text:       '#f0dda0',
      textDim:    '#7a6a3a',
      accent:     '#ffcc44',
      accentGlow: 'rgba(255,204,68,0.4)',
    },
    colors: {
      default:        '#2a2010',
      default_border: '#3a3020',
      active:         '#ffcc44',
      compare:        '#ff6622',
      pivot:          '#ff4400',
      sorted:         '#aaaa00',
    },
  },

  ocean: {
    name: 'Ocean',
    font: "'Share Tech Mono', monospace",
    displayFont: "'Bebas Neue', sans-serif",
    ui: {
      bg:         '#010e1a',
      panel:      '#021828',
      border:     '#0a2a3a',
      text:       '#a0d8ef',
      textDim:    '#2a5a7a',
      accent:     '#00aaff',
      accentGlow: 'rgba(0,170,255,0.4)',
    },
    colors: {
      default:        '#041e2e',
      default_border: '#0a2e3e',
      active:         '#00aaff',
      compare:        '#ff4488',
      pivot:          '#00ffaa',
      sorted:         '#0044aa',
    },
  },

  lava: {
    name: 'Lava',
    font: "'Share Tech Mono', monospace",
    displayFont: "'Bebas Neue', sans-serif",
    ui: {
      bg:         '#0f0800',
      panel:      '#1a0e00',
      border:     '#2e1e00',
      text:       '#ffe0a0',
      textDim:    '#6a4400',
      accent:     '#ff6600',
      accentGlow: 'rgba(255,102,0,0.4)',
    },
    colors: {
      default:        '#2a1400',
      default_border: '#3a2200',
      active:         '#ff6600',
      compare:        '#ffcc00',
      pivot:          '#ff0000',
      sorted:         '#aa2200',
    },
  },

  mint: {
    name: 'Mint',
    font: "'Share Tech Mono', monospace",
    displayFont: "'Bebas Neue', sans-serif",
    ui: {
      bg:         '#f0fff8',
      panel:      '#e0fff0',
      border:     '#a0ddbb',
      text:       '#0a2a1a',
      textDim:    '#5a9a7a',
      accent:     '#00aa66',
      accentGlow: 'rgba(0,170,102,0.3)',
    },
    colors: {
      default:        '#bbeecc',
      default_border: '#99ddaa',
      active:         '#00aa66',
      compare:        '#cc2266',
      pivot:          '#ee8800',
      sorted:         '#006633',
    },
  },

  void: {
    name: 'Void',
    font: "'Share Tech Mono', monospace",
    displayFont: "'Bebas Neue', sans-serif",
    ui: {
      bg:         '#000000',
      panel:      '#080808',
      border:     '#111111',
      text:       '#aaaaaa',
      textDim:    '#333333',
      accent:     '#ffffff',
      accentGlow: 'rgba(255,255,255,0.3)',
    },
    colors: {
      default:        '#111111',
      default_border: '#222222',
      active:         '#ffffff',
      compare:        '#888888',
      pivot:          '#cccccc',
      sorted:         '#444444',
    },
  },
};